### ISSUE TITLE
Auto formatting number column can cause confusion

### ISSUE THREAD

**Issue by arky** [CJWorkbench/loadurl#5]
I think auto formatting can confuse users,  in the following example the 'Year' is automatically formatted as a number. 

![image](https://user-images.githubusercontent.com/808895/88757579-95fb6d80-d190-11ea-847b-7a364907d141.png)

URI https://raw.githubusercontent.com/nipn-laos/dashboard-v2/master/data/agri1.csv

**Comment by adamhooper** [comment]
This is an issue with the default number format. (Technically, there's no such thing as _not_ formatting. The question is around _how_ to format, not _whether_ to format.)

We're aware that "year" and "id" are two common instances in which the default number format is confusing. However, there's a design trade-off: if we tack on special case after special case, Workbench behaves more _magically_ (which is good) ... and _less understandably_ (which is bad).

Handling "year" and "id" columns specially would benefit many English-language users; most other users wouldn't see a difference; and _some_ other users would be frustrated because their columns would be formatted according to rules they don't understand. (Yes, a comma in "year" is frustrating; but the behavior is so simple you can understand why it's there. Magical rules are _more_ frustrating when they err, because as a user you can't tell what went wrong.)

All that to say: it's a tricky design decision.

This issue certainly isn't "resolved" (nor will it ever be, even if we change the rules...). But I'll mark this "closed" on GitHub. Your opinion will be tallied in our internal tools, and it will inform future design decisions.

**Comment by arky** [comment]
Gotcha! Thanks @adamhooper
